# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
  cd BuildSystem 
  ./doBuild.sh boost
displayName: 'Compile the BOOST versions of SPM'

- script: |
  cd BuildSystem 
  ./doBuild.sh release
displayName: 'Compile the release versions of SPM'

